import { AirdropRule } from "@/lib/types";

export const AIRDROP_RULES: AirdropRule[] = [
  {
    id: "jupiter-ecosystem-s2",
    project: "Jupiter Exchange",
    network: "solana",
    category: "defi",
    status: "upcoming",
    officialClaimUrl: "https://jup.ag",
    sourceUrl: "https://x.com/JupiterExchange",
    trustedDomains: ["jup.ag"],
    estimatedValue: "$200–$800",
    description: "Jupiter Season 2 airdrop for active DeFi traders. Snapshot based on swap volume and engagement.",
    tags: ["DEX", "Swap", "Season 2"],
    timeline: { announcedAt: "2026-01-20", snapshotAt: "2026-03-15", claimOpensAt: "2026-03-22", claimEndsAt: "2026-04-30" },
    riskLevel: "low",
    checks: { minRecentTransactions: 25, minTokenAccounts: 4, maxLastActiveDays: 45 },
  },
  {
    id: "tensor-loyalty",
    project: "Tensor NFT",
    network: "solana",
    category: "nft",
    status: "active",
    officialClaimUrl: "https://www.tensor.trade",
    sourceUrl: "https://x.com/tensor_hq",
    trustedDomains: ["tensor.trade"],
    estimatedValue: "$50–$300",
    description: "Tensor loyalty rewards for NFT traders. Requires holding or trading NFTs on Tensor marketplace.",
    tags: ["NFT", "Trading", "Loyalty"],
    timeline: { announcedAt: "2026-01-10", snapshotAt: "2026-02-25", claimOpensAt: "2026-03-01", claimEndsAt: "2026-04-10" },
    riskLevel: "medium",
    checks: { minNftCount: 1, minRecentTransactions: 10, maxLastActiveDays: 60 },
  },
  {
    id: "helius-devs",
    project: "Helius Builders",
    network: "solana",
    category: "infrastructure",
    status: "upcoming",
    officialClaimUrl: "https://www.helius.dev",
    sourceUrl: "https://x.com/heliuslabs",
    trustedDomains: ["helius.dev"],
    estimatedValue: "$100–$500",
    description: "Helius developer airdrop for active on-chain builders and RPC power users.",
    tags: ["RPC", "Dev", "Infrastructure"],
    timeline: { announcedAt: "2026-02-02", snapshotAt: "2026-03-28", claimOpensAt: "2026-04-02", claimEndsAt: "2026-05-05" },
    riskLevel: "low",
    checks: { minSolBalance: 0.03, minTokenAccounts: 2, minRecentTransactions: 8, maxLastActiveDays: 90 },
  },
  {
    id: "drift-trader-rewards",
    project: "Drift Protocol",
    network: "solana",
    category: "defi",
    status: "snapshot_taken",
    officialClaimUrl: "https://www.drift.trade",
    sourceUrl: "https://x.com/DriftProtocol",
    trustedDomains: ["drift.trade"],
    estimatedValue: "$150–$600",
    description: "Drift perpetual trading rewards. Snapshot taken — eligible traders can now claim.",
    tags: ["Perps", "Trading", "DeFi"],
    timeline: { announcedAt: "2026-01-15", snapshotAt: "2026-02-20", claimOpensAt: "2026-03-05", claimEndsAt: "2026-04-05" },
    riskLevel: "medium",
    checks: { minRecentTransactions: 30, requiresAnyTokens: ["USDC", "JUP", "BONK"], maxLastActiveDays: 30 },
  },
  {
    id: "phantom-community-quests",
    project: "Phantom Wallet Quests",
    network: "solana",
    category: "consumer",
    status: "active",
    officialClaimUrl: "https://phantom.app",
    sourceUrl: "https://x.com/phantom",
    trustedDomains: ["phantom.app"],
    estimatedValue: "$20–$150",
    description: "Community quest rewards for Phantom wallet users. Low barrier to entry.",
    tags: ["Wallet", "Quests", "Consumer"],
    timeline: { announcedAt: "2026-01-08", snapshotAt: "2026-03-01", claimOpensAt: "2026-03-18", claimEndsAt: "2026-04-18" },
    riskLevel: "high",
    checks: { minSolBalance: 0.01, minTokenAccounts: 1, minRecentTransactions: 3 },
  },
  {
    id: "raydium-lp-rewards",
    project: "Raydium LP Rewards",
    network: "solana",
    category: "defi",
    status: "active",
    officialClaimUrl: "https://raydium.io",
    sourceUrl: "https://x.com/RaydiumProtocol",
    trustedDomains: ["raydium.io"],
    estimatedValue: "$100–$400",
    description: "Raydium liquidity provider rewards for CLMM and AMM pool participants.",
    tags: ["AMM", "LP", "DeFi"],
    timeline: { announcedAt: "2026-01-25", snapshotAt: "2026-02-28", claimOpensAt: "2026-03-10", claimEndsAt: "2026-05-01" },
    riskLevel: "low",
    checks: { minTokenAccounts: 5, minRecentTransactions: 20, maxLastActiveDays: 60, requiresAnyTokens: ["USDC", "SOL", "RAY"] },
  },
  {
    id: "marinade-stakers",
    project: "Marinade Finance",
    network: "solana",
    category: "defi",
    status: "upcoming",
    officialClaimUrl: "https://marinade.finance",
    sourceUrl: "https://x.com/MarinadeFinance",
    trustedDomains: ["marinade.finance"],
    estimatedValue: "$80–$350",
    description: "Marinade staking rewards airdrop for mSOL holders and liquid stakers.",
    tags: ["Staking", "LST", "DeFi"],
    timeline: { announcedAt: "2026-02-05", snapshotAt: "2026-04-01", claimOpensAt: "2026-04-15", claimEndsAt: "2026-05-30" },
    riskLevel: "low",
    checks: { minSolBalance: 0.1, minTokenAccounts: 2, maxLastActiveDays: 90 },
  },
  {
    id: "marginfi-early-users",
    project: "marginfi Early Users",
    network: "solana",
    category: "defi",
    status: "upcoming",
    officialClaimUrl: "https://app.marginfi.com",
    sourceUrl: "https://x.com/marginfi",
    trustedDomains: ["marginfi.com"],
    estimatedValue: "$200–$1000",
    description: "marginfi lending protocol airdrop for early depositors and borrowers.",
    tags: ["Lending", "DeFi", "Early Access"],
    timeline: { announcedAt: "2026-02-10", snapshotAt: "2026-03-20", claimOpensAt: "2026-04-01", claimEndsAt: "2026-05-15" },
    riskLevel: "low",
    checks: { minSolBalance: 0.05, minTokenAccounts: 3, minRecentTransactions: 15, maxLastActiveDays: 60 },
  },
  {
    id: "kamino-lenders",
    project: "Kamino Finance",
    network: "solana",
    category: "defi",
    status: "snapshot_taken",
    officialClaimUrl: "https://kamino.finance",
    sourceUrl: "https://x.com/KaminoFinance",
    trustedDomains: ["kamino.finance"],
    estimatedValue: "$150–$700",
    description: "Kamino liquidity strategy rewards for vault depositors. Snapshot already taken.",
    tags: ["Vaults", "Yield", "DeFi"],
    timeline: { announcedAt: "2026-01-18", snapshotAt: "2026-02-15", claimOpensAt: "2026-03-01", claimEndsAt: "2026-04-20" },
    riskLevel: "medium",
    checks: { minTokenAccounts: 4, minRecentTransactions: 12, requiresAnyTokens: ["USDC", "SOL", "JUP"], maxLastActiveDays: 45 },
  },
  {
    id: "magic-eden-rewards",
    project: "Magic Eden Rewards",
    network: "solana",
    category: "nft",
    status: "active",
    officialClaimUrl: "https://magiceden.io",
    sourceUrl: "https://x.com/MagicEden",
    trustedDomains: ["magiceden.io"],
    estimatedValue: "$30–$200",
    description: "Magic Eden marketplace rewards for NFT buyers, sellers, and listers.",
    tags: ["NFT", "Marketplace", "Trading"],
    timeline: { announcedAt: "2026-01-22", snapshotAt: "2026-02-22", claimOpensAt: "2026-03-08", claimEndsAt: "2026-04-25" },
    riskLevel: "medium",
    checks: { minNftCount: 1, minRecentTransactions: 5, maxLastActiveDays: 90 },
  },
  {
    id: "solend-depositors",
    project: "Solend Protocol",
    network: "solana",
    category: "defi",
    status: "upcoming",
    officialClaimUrl: "https://solend.fi",
    sourceUrl: "https://x.com/solendprotocol",
    trustedDomains: ["solend.fi"],
    estimatedValue: "$50–$250",
    description: "Solend lending rewards for longtime depositors and governance participants.",
    tags: ["Lending", "Governance", "DeFi"],
    timeline: { announcedAt: "2026-02-08", snapshotAt: "2026-03-25", claimOpensAt: "2026-04-05", claimEndsAt: "2026-05-20" },
    riskLevel: "low",
    checks: { minSolBalance: 0.02, minTokenAccounts: 2, minRecentTransactions: 10, maxLastActiveDays: 120 },
  },
  {
    id: "orca-traders",
    project: "Orca DEX",
    network: "solana",
    category: "defi",
    status: "upcoming",
    officialClaimUrl: "https://www.orca.so",
    sourceUrl: "https://x.com/orca_so",
    trustedDomains: ["orca.so"],
    estimatedValue: "$75–$400",
    description: "Orca Whirlpool concentrated liquidity provider and trader rewards.",
    tags: ["DEX", "CLMM", "Swap"],
    timeline: { announcedAt: "2026-02-14", snapshotAt: "2026-04-10", claimOpensAt: "2026-04-20", claimEndsAt: "2026-06-01" },
    riskLevel: "low",
    checks: { minTokenAccounts: 3, minRecentTransactions: 18, maxLastActiveDays: 60 },
  },
  {
    id: "pyth-stakers",
    project: "Pyth Network",
    network: "solana",
    category: "infrastructure",
    status: "active",
    officialClaimUrl: "https://staking.pyth.network",
    sourceUrl: "https://x.com/PythNetwork",
    trustedDomains: ["pyth.network"],
    estimatedValue: "$100–$600",
    description: "Pyth oracle network staking rewards for PYTH token stakers and governance voters.",
    tags: ["Oracle", "Staking", "Governance"],
    timeline: { announcedAt: "2026-01-30", snapshotAt: "2026-03-05", claimOpensAt: "2026-03-12", claimEndsAt: "2026-05-01" },
    riskLevel: "low",
    checks: { minSolBalance: 0.01, minTokenAccounts: 2, minRecentTransactions: 5, maxLastActiveDays: 120 },
  },
  {
    id: "step-finance-s2",
    project: "Step Finance",
    network: "solana",
    category: "consumer",
    status: "upcoming",
    officialClaimUrl: "https://step.finance",
    sourceUrl: "https://x.com/StepFinance_",
    trustedDomains: ["step.finance"],
    estimatedValue: "$40–$180",
    description: "Step Finance portfolio tracker Season 2 rewards for active dashboard users.",
    tags: ["Portfolio", "Analytics", "Season 2"],
    timeline: { announcedAt: "2026-02-18", snapshotAt: "2026-04-05", claimOpensAt: "2026-04-18", claimEndsAt: "2026-06-01" },
    riskLevel: "low",
    checks: { minSolBalance: 0.01, minTokenAccounts: 3, maxLastActiveDays: 90 },
  },
];
