import { AirdropRule } from "@/lib/types";

export const AIRDROP_RULES: AirdropRule[] = [
  {
    id: "jupiter-ecosystem-s2",
    project: "Jupiter Ecosystem",
    network: "solana",
    category: "defi",
    status: "upcoming",
    officialClaimUrl: "https://jup.ag",
    sourceUrl: "https://x.com/JupiterExchange",
    trustedDomains: ["jup.ag"],
    timeline: {
      announcedAt: "2026-01-20",
      snapshotAt: "2026-03-15",
      claimOpensAt: "2026-03-22",
      claimEndsAt: "2026-04-30",
    },
    riskLevel: "low",
    checks: {
      minRecentTransactions: 25,
      minTokenAccounts: 4,
      maxLastActiveDays: 45,
    },
  },
  {
    id: "tensor-loyalty",
    project: "Tensor Loyalty",
    network: "solana",
    category: "nft",
    status: "active",
    officialClaimUrl: "https://www.tensor.trade",
    sourceUrl: "https://x.com/tensor_hq",
    trustedDomains: ["tensor.trade"],
    timeline: {
      announcedAt: "2026-01-10",
      snapshotAt: "2026-02-25",
      claimOpensAt: "2026-03-01",
      claimEndsAt: "2026-04-10",
    },
    riskLevel: "medium",
    checks: {
      minNftCount: 1,
      minRecentTransactions: 10,
      maxLastActiveDays: 60,
    },
  },
  {
    id: "helius-devs",
    project: "Helius Builders",
    network: "solana",
    category: "infrastructure",
    status: "upcoming",
    officialClaimUrl: "https://www.helius.dev",
    sourceUrl: "https://x.com/heliuslabs",
    trustedDomains: ["helius.dev"],
    timeline: {
      announcedAt: "2026-02-02",
      snapshotAt: "2026-03-28",
      claimOpensAt: "2026-04-02",
      claimEndsAt: "2026-05-05",
    },
    riskLevel: "low",
    checks: {
      minSolBalance: 0.03,
      minTokenAccounts: 2,
      minRecentTransactions: 8,
      maxLastActiveDays: 90,
    },
  },
  {
    id: "drift-trader-rewards",
    project: "Drift Trader Rewards",
    network: "solana",
    category: "defi",
    status: "snapshot_taken",
    officialClaimUrl: "https://www.drift.trade",
    sourceUrl: "https://x.com/DriftProtocol",
    trustedDomains: ["drift.trade"],
    timeline: {
      announcedAt: "2026-01-15",
      snapshotAt: "2026-02-20",
      claimOpensAt: "2026-03-05",
      claimEndsAt: "2026-04-05",
    },
    riskLevel: "medium",
    checks: {
      minRecentTransactions: 30,
      requiresAnyTokens: ["USDC", "JUP", "BONK"],
      maxLastActiveDays: 30,
    },
  },
  {
    id: "phantom-community-quests",
    project: "Wallet Community Quests",
    network: "solana",
    category: "consumer",
    status: "active",
    officialClaimUrl: "https://phantom.app",
    sourceUrl: "https://x.com/phantom",
    trustedDomains: ["phantom.app"],
    timeline: {
      announcedAt: "2026-01-08",
      snapshotAt: "2026-03-01",
      claimOpensAt: "2026-03-18",
      claimEndsAt: "2026-04-18",
    },
    riskLevel: "high",
    checks: {
      minSolBalance: 0.01,
      minTokenAccounts: 1,
      minRecentTransactions: 3,
    },
  },
];
